<script>
    window.mapiDemoBaseUrl = "<?php echo $block->getBaseUrl();?>";
</script>
<div id="mapi_main_container" class="mapi_main_container" data-bind="scope:'container'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<?php echo $this->getChildHtml(); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
        }
    }
</script>